version: '3'
services:
  nginx:
    container_name: ck-nginx
    hostname: ck-nginx
    image: nginx:1.17.6
    environment:
      TZ: Asia/Shanghai
    restart: always
    expose:
      - 80
      - 443
    ports:
      - 443:443
      - 80:80
    volumes:
      - /usr/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx/logs:/var/log/nginx
      - /usr/local/nginx/cert:/etc/nginx/cert
      - /etc/localtime:/etc/localtime